# vim:ft=kitty

## name:     porple
## author:   mise
## license:  KYLE
## upstream: https://feck.off
## blurb:    purp


# foreground
background #1f003d
background_opacity 0.85

color1 #cc5656 #red
color9 #ff7d5c


color2 #2cbc66 #green
color10 #33ff92


color3 #c3a350 #was yellow
color11 #fde37d



color13 #FC0384 #magenta
color5 #D60270

color4 #1387d5 #blue
color12 #1ecbff

color7 #B1ACF7
color15 #dfd1f7
