monitorrule=name:^DP-1$,width:2560,height:1440,refresh:144,x:1920,y:0
monitorrule=name:^HDMI-A-1$,width:1920,height:1080,refresh:75,x:0,y:0

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,monitor_name:DP-1,layout_name:tile,no_hide:1
tagrule=id:1,monitor_name:HDMI-A-1,layout_name:tile,no_hide:0

tagrule=id:2,monitor_name:DP-1,layout_name:tile,no_hide:1
tagrule=id:2,monitor_name:HDMI-A-1,layout_name:tile,no_hide:0

tagrule=id:3,monitor_name:DP-1,layout_name:tile,no_hide:1
tagrule=id:3,monitor_name:HDMI-A-1,layout_name:right_tile,no_hide:1

tagrule=id:4,monitor_name:DP-1,layout_name:tile,no_hide:1
tagrule=id:4,monitor_name:HDMI-A-1,layout_name:right_tile,no_hide:1


tagrule=id:5,layout_name:tile,no_hide:1
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile



# layer rule "mmsg watch last_open_surface"
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
layerrule=animation_type_open:zoom,layer_name:wofi
layerrule=animation_type_close:zoom,layer_name:wofi
layerrule=animation_type_open:slide,layer_name:swaync-control-center
layerrule=animation_type_close:slide,layer_name:swaync-control-center


layerrule=noblur:1,layer_name:rofi
layerrule=noblur:1,layer_name:wofi
layerrule=noblur:1,layer_name:selection

windowrule=ignore_minimize:1,appid:.*
windowrule=tags:1,ignore_minimize:1,monitor:DP-1,title:^(Steam)$,appid:^(steam)$
windowrule=isfloating:1,title:^(?!Steam).*$,appid:^(steam)$
windowrule=isfloating:1,title:^(Steam Settings)$,appid:^(steam)$

#move games to monitor 2
windowrule=tags:2,monitor:DP-1,isfullscreen:1,title:^RetroArch .+$
windowrule=tags:2,monitor:DP-1,isfullscreen:1,appid:^Azahar$, title: ^(Azahar 2.*)$
windowrule=tags:1,monitor:DP-1,isfullscreen:1,title:^RetroArch$
windowrule=tags:2,monitor:DP-1,isfullscreen:1,appid:^(steam_app_\d+)$
windowrule=tags:2,monitor:DP-1,isfullscreen:1,appid:^(steam_proton)$
windowrule=tags:2,monitor:DP-1,isfullscreen:1,appid:^(Minecraft.*)$
windowrule=tags:2,monitor:DP-1,isfullscreen:1,appid:^(gamescope)$
windowrule=tags:2,monitor:DP-1,isfullscreen:1,appid:^(proton-game)$
windowrule=tags:2,monitor:DP-1,isfullscreen:1,appid:^(.*.exe)$
windowrule=tags:2,monitor:DP-1,isfullscreen:1,title:^(.*.exe)$
windowrule=tags:2,monitor:DP-1,isfullscreen:1,appid:^(.*.x86)$
windowrule=tags:3,monitor:HDMI-A-1,appid:vesktop

windowrule=isfloating:1,width:650,height:700,offsetx:100,offsety:-100,title:Volume Control
windowrule=isfloating:1,width:433,height:250,offsetx:100,offsety:-100,title:btop-mem
windowrule=isfloating:1,width:838,height:488,offsetx:100,offsety:-100,title:btop-cpu
windowrule=isfloating:1,width:433,height:250,offsetx:-72,offsety:-100,title:btop-net
windowrule=isfloating:1,width:1200,height:1200,title:btop-float
windowrule=isfloating:1,width:400,height:500,title:KCalc
windowrule=isfloating:1,width:500,height:350,offsety:-100,title:calcure
windowrule=isfloating:1,width:500,height:290,offsetx:-100,offsety:99,appid:hyprland-share-picker
windowrule=isfloating:1,width:900,height:700,title:Select one or more files to open
windowrule=isfloating:1,width:1300,height:900,offsety:-30,title:Open Images — Krita
windowrule=isfloating:1,width:1300,height:900,offsety:-30,title:Library,appid:firefox
windowrule=isfloating:1,width:1300,height:900,offsety:-30,title:Preferences,appid:gimp
windowrule=isfloating:1,width:800,height:640,offsety:-30,title:Save Image — Gwenview
windowrule=isfloating:1,width:1000,height:850,offsety:-30,title:Save Image As — KolourPaint
#windowrule=focused_opacity:0.95,appid:org.kde.dolphin

windowrule=unfocused_opacity:1.0,title:^(.*Discord \| General.*)$|^(.*Discord \| morbuis.*)$
windowrule=unfocused_opacity:1.0,title:^(.*Picture-in-Picture.*)$




windowrule=tags:5,istagsilent:1,title:kitty-gimp,appid:kitty
